# TODO: copy xinitrc
- name: System Configuration
  hosts: localhost
  connection: local

  vars:
    user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    home_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}"
    config_dir: "{{ home_dir }}/.config"
    project_dir: "{{ home_dir }}/projects"
    dotfiles_dir: "{{ project_dir }}/dotfiles" 

  tasks: 
    - name: Create 'projects' directory
      ansible.builtin.file:
        path: "{{ project_dir }}"
        owner: "{{ user }}"
        state: directory

    - name: Create '.config' directory
      ansible.builtin.file:
        path: "{{ config_dir }}"
        owner: "{{ user }}"
        state: directory

    - name: Check dotfiles directory
      stat:
        path: "{{ dotfiles_dir }}"
      register: dotfiles

    - name: Clone 'dotfiles' repo
      git: 
        repo: "https://github.com/jackboxx/dotfiles"
        dest: "{{ dotfiles_dir }}"
      when: not dotfiles.stat.exists 

    - name: Create symbolic links for dotfiles
      ansible.builtin.file:
        src: "{{ dotfiles_dir }}/{{ item }}"
        dest:  "{{ config_dir }}/{{ item }}"
        owner: "{{ user }}"
        state: link
      loop: 
        - nvim
        - tmux 
        - i3
        - alacritty
        - gitui
        - rofi
        - polybar
        - neofetch
        - picom.conf

    - name: Check .zshrc
      stat:
        path: "{{ home_dir }}/.zshrc"
      register: zshrc

    - name: Create symbolic links for .zshrc
      ansible.builtin.file:
        src: "{{ dotfiles_dir }}/.zshrc"
        dest:  "{{ home_dir }}/.zshrc"
        owner: "{{ user }}"
        state: link
      when: not zshrc.stat.exists

    - name: Copy GitHub access token
      ansible.builtin.copy:
        src: "{{ dotfiles_dir }}/private/github/access-token"
        dest: "/tmp/token"
        decrypt: true

    - name: Authentication GitHub with access token
      ansible.builtin.shell: |
        gh auth login --with-token < /tmp/token

    - name: Create group for keyboard firmware
      group:
        name: plugdev
        state: present
      become: true

    - name: Add user to keyboard firmware group
      ansible.builtin.user:
        name: "{{ lookup('ansible.builtin.env', 'USER') }}"
        groups: plugdev
        append: yes
      become: true

    - name: Check keyboard file
      stat:
        path: /etc/udev/rules.d/50-zsa.rules
      register: keyboard

    - name: Add keyboard firmware configuration file
      copy:
        dest: /etc/udev/rules.d/50-zsa.rules
        content: |
          # Rules for Oryx web flashing and live training
          KERNEL=="hidraw*", ATTRS{idVendor}=="16c0", MODE="0664", GROUP="plugdev"
          KERNEL=="hidraw*", ATTRS{idVendor}=="3297", MODE="0664", GROUP="plugdev"
          # Wally Flashing rules for the Moonlander and Planck EZ
          SUBSYSTEMS=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="df11", \
              MODE:="0666", \
              SYMLINK+="stm32_dfu"
      become: true
      when: not keyboard.stat.exists

